# Generated by Django 5.2.1 on 2025-05-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxeRoutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('point_depart', models.CharField(max_length=100)),
                ('point_arrivee', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('coords', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', models.CharField(max_length=100)),
                ('point_arrivee', models.CharField(max_length=100)),
                ('temps_total_min', models.IntegerField(default=0)),
                ('heure_pointe', models.CharField(default='matin', max_length=10)),
                ('axes', models.ManyToManyField(to='recommandations.axeroutier')),
            ],
        ),
        migrations.CreateModel(
            name='TempsTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_pointe', models.CharField(max_length=10)),
                ('temps_moyen_min', models.IntegerField()),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandations.axeroutier')),
            ],
        ),
    ]
